Extended lint applied
SpoonX/aurelia-orm pull request #226
Opened 2016-09-28 16:10 UTC by doktordirk

preview

2016-09-28 16:11 UTC, doktordirk commented on src/repository.js
> +      if ({}.hasOwnProperty.call(associations, property)) {
that's http://eslint.org/docs/rules/guard-for-in (together with http://eslint.org/docs/rules/no-prototype-builtins )

2016-09-28 16:12 UTC, doktordirk commented on src/entity.js
> +      .then(updated => { response = updated; })
that's http://eslint.org/docs/rules/no-return-assign

2016-10-01 13:47 UTC, doktordirk commented
@RWOverdijk

2016-10-01 16:07 UTC, RWOverdijk requested changes

2016-10-01 16:07 UTC, RWOverdijk commented on src/repository.js
> +
Why the newline? Is that really a linting rule?

2016-10-01 16:07 UTC, RWOverdijk commented on src/entity.js
> +      .then(updated => { response = updated; })
Mhm. I kind of get it, but it's convenient here. So by rule, it should then be an assignment followed by a return?

Either way, I think we can lose the curly braces, and the semicolon?

2016-10-01 16:07 UTC, RWOverdijk commented on src/decorator/idProperty.js
> + * @deocator
deocator?

2016-10-01 16:07 UTC, RWOverdijk commented on src/component/association-select.js
> +      .catch(error => { this.error = error; });
Also return, in case it's going to be used. This is a BC break.

2016-10-01 16:59 UTC, doktordirk commented on src/entity.js
> +      .then(updated => { response = updated; })
that.s contradictory. either we use the rule and then we need curlies(+semicolons) or we allow returning assignments. unfortunatelly they don.t have an exception for fat arrows (yet)

2016-10-01 17:00 UTC, doktordirk commented on src/repository.js
> +
hmm. i might need to recheck.

2016-10-01 17:02 UTC, doktordirk commented on src/decorator/idProperty.js
> + * @deocator
that s from auto jsdocs. admitably that s not very consistent. others include @export and @memberOf. might get useful for auto doc generation (which i wanted to recheck)

2016-10-01 17:03 UTC, doktordirk commented on src/component/association-select.js
> +      .catch(error => { this.error = error; });
so i guess we just disable the rule then

2016-10-01 18:55 UTC, doktordirk commented
re: 
```
then(updated => { response = updated; })
      @RWOverdijk
RWOverdijk 3 hours ago
Mhm. I kind of get it, but it's convenient here. So by rule, it should then be an assignment followed by a return?
Either way, I think we can lose the curly braces, and the semicolon?
```
how?

2016-10-01 18:58 UTC, doktordirk commented on src/repository.js
> +
ah, ähm yes, that's ~ 'newline after variable declaration' or so (var, let , const)

2016-10-03 06:38 UTC, doktordirk commented on src/decorator/idProperty.js
> + * @deocator
fixed

2016-10-03 06:39 UTC, doktordirk commented on src/component/association-select.js
> +      .catch(error => { this.error = error; });
fixed

2016-10-04 09:59 UTC, RWOverdijk commented on src/entity.js
> +      .then(updated => { response = updated; })
Allow return assignments :)

2016-10-04 10:00 UTC, RWOverdijk approved these changes

2016-10-04 10:01 UTC, RWOverdijk commented
Allow return statements can be done later, wouldn't break current linting so no rush.

2016-10-04 10:02 UTC, merged