Feat/find one
SpoonX/aurelia-orm pull request #251
Opened 2017-01-04 11:18 UTC by bas080

2017-01-10 09:05 UTC, RWOverdijk requested changes

2017-01-10 09:05 UTC, RWOverdijk commented on src/repository.js
> +    return this.find(...args).then(records => {
Add a limit 1 to the criteria.

2017-01-10 09:05 UTC, RWOverdijk commented on src/repository.js
> +      return Promise.reject();
Why a reject?

2017-01-10 09:05 UTC, RWOverdijk commented on test/repository.spec.js
> +        expect(response.method).toEqual('GET')
This doesn't really test the method.

2017-01-10 09:05 UTC, VMBindraban commented on src/repository.js
> +    return this.find(...args).then(records => {
Add `limit: 1` to criteria. You can override this. (since it's a findOne)

2017-01-10 09:15 UTC, bas080 commented on src/repository.js
> +    return this.find(...args).then(records => {
Should it then no longer contain the length checks?

2017-01-10 09:15 UTC, bas080 commented on src/repository.js
> +      return Promise.reject();
If it fails to find**One** it should reject.

2017-01-10 09:17 UTC, bas080 commented on test/repository.spec.js
> +        expect(response.method).toEqual('GET')
I could mock the find method. That way I can test the logic in the `then`.

2017-01-10 14:57 UTC, RWOverdijk requested changes

2017-01-10 14:57 UTC, RWOverdijk commented on src/repository.js
> +      return Promise.reject();
https://github.com/bas080/aurelia-orm/blob/193be843c02b423574b9e626279e7ffd6a3d2278/src/repository.js#L143

2017-01-11 10:16 UTC, bas080 commented
@RWOverdijk, added requested changes.

2017-01-11 12:33 UTC, closed without merging