feat (identifier decorator): add identifier decorator to support the same resource key for different endpoints
SpoonX/aurelia-orm pull request #290
Opened 2017-05-19 12:56 UTC by mroseboom

At this moment it's not possible to use the same resource key for multiple endpoints. With the identifier decorator this will be possible and when no given it will fallback to the resource decorator.

2017-05-19 13:02 UTC, RWOverdijk requested changes

2017-05-19 13:02 UTC, RWOverdijk commented on doc/decorators.md
> +When left empty, the name of the class (.toLowerCase()) will be used as the resource name. This is usually fine.
Maybe add a note that this is a bad idea for bundling, as the names of classes get renamed.

2017-05-19 13:02 UTC, RWOverdijk commented on src/entity-manager.js
> +    let reference = (OrmMetadata.forTarget(EntityClass).fetch('identifier') !== null)
This works fine, but I thought I'd show you an alternative:

```js
let meta = OrmMetadata.forTarget(EntityClass);

 this.entities[meta.fetch('identifier', meta.fetch('resource'))] = EntityClass;
```

2017-05-19 13:02 UTC, RWOverdijk commented on src/entity-manager.js
> +    let identifier = entity;
Align consecutive assignments:

```js
let foo  = 'bar';
let cake = 'bat';
```

2017-05-19 13:02 UTC, RWOverdijk commented on test/decorator/identifier.spec.js
> +// describe('@identifier()', function() {
Why is this commented out?

2017-05-19 13:04 UTC, RWOverdijk commented
👏 awesome! This is near a perfect PR. :)

I've added some minor feedback, and I have one request concerning the commit message. Could you change it to:

`feat(project): add identity decorator as to support duplicate resources`

Thank you for your contribution, it's appreciated.

2017-05-19 13:07 UTC, mroseboom commented on test/decorator/identifier.spec.js
> +// describe('@identifier()', function() {
Oops, must be uncommented ;)

2017-05-19 13:17 UTC, mroseboom commented on doc/decorators.md
> +When left empty, the name of the class (.toLowerCase()) will be used as the resource name. This is usually fine.
Can you explain further why this have a negative effect for bundling? And is this applied when you use this decorator?

2017-05-19 13:25 UTC, RWOverdijk commented on doc/decorators.md
> +When left empty, the name of the class (.toLowerCase()) will be used as the resource name. This is usually fine.
@mroseboom It's the same for resource. When bundled, and minified, the class names get changed (to be shorter). Sometimes even when transpiled. Your identifier is a string, which will then no longer match.

2017-05-19 14:08 UTC, RWOverdijk commented
I'll re-review this when I get home :) One thing I'd add is an additional test with actual duplicates. One that fails to satisfy the need for unique entities, and one that succeeds due to the newly added identifier. :)

2017-05-20 10:36 UTC, mroseboom commented
Were should i place this (missing) unit tests? Within the `test/decorator/identifier.spec.js` file?

2017-05-22 06:16 UTC, RWOverdijk commented
Exactly like that :) I'm sorry it took this long to get back to you.

2017-05-22 06:16 UTC, RWOverdijk approved these changes

2017-05-22 06:24 UTC, merged