Throw exception on invalid API resource endpoint return,
SpoonX/aurelia-orm pull request #304
Opened 2017-06-23 16:11 UTC by mreiche

That fixes https://github.com/SpoonX/aurelia-orm/issues/303

2017-06-26 07:11 UTC, RWOverdijk requested changes
Could you update the tests and change your commit messages according to the [guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)?

2017-06-26 07:11 UTC, RWOverdijk commented on src/entity.js
> +        if (created===null||created[this.getIdProperty()]===undefined) throw new Error('The API resource did not return the id property "'+this.getIdProperty()+'"');
Please follow the code conventions. Spaces surrounding or statement and curly braces.

2017-06-26 09:42 UTC, mreiche commented on src/entity.js
> +        if (created===null||created[this.getIdProperty()]===undefined) throw new Error('The API resource did not return the id property "'+this.getIdProperty()+'"');
Of course. Sorry for that.

2017-06-26 10:46 UTC, mreiche commented
Ok, I'm going to fix the tests now seriously.

2017-06-26 11:06 UTC, mreiche commented
Hmm.. I have no glue how to implement that "positive false" test for the exception. I'm not really familiar with Javascript/Karma. Where are the services mocked? Any tips and hints?

2017-06-26 11:45 UTC, RWOverdijk commented
You changed the error message, so the check for the error message needs to be different. It's in the test directory.

Re: commit messages, They're still not correct. Use the imperative, present tense. Also, the format is: `type(scope): message`. Example:

`test(repository): update exception message asserts`

2017-06-26 12:26 UTC, mreiche commented
> You changed the error message, so the check for the error message needs to be different. It's in the test directory.

This is not the only problem. I fixed that locally. But I'm unable to avoid:
```
ERROR: 'Potentially unhandled rejection [1] Error: The API resource did not return @idProperty for entity.
    at eval (http://localhost:9876/base/src/entity.js:174:15)
    at tryCatchReject (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:1188:30)
    at runContinuation1 (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:1147:4)
    at Fulfilled.when (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:935:4)
    at Thenable.Pending.run (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:826:13)
    at Scheduler._drain (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:102:19)
    at Scheduler.drain (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:67:9)
    at MutationObserver.run (http://localhost:9876/base/jspm_packages/system-polyfills.src.js?9e8733cdc1a619a0238d6b06eeca4ba4733673d7:273:4)'
Chrome 58.0.3029 (Mac OS X 10.12.5) Entity .save() Should call .create on REST without an ID. (custom entity) FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

2017-07-04 08:12 UTC, RWOverdijk commented
@mreiche Do you need my help with this?

2017-07-04 08:18 UTC, mreiche commented
> Do you need my help with this?
Yes

2020-11-25 12:40 UTC, closed without merging